version: '3.4'

services:
  webaggregator:
    image: ${DOCKER_REGISTRY-}webaggregator
    container_name: webaggregator
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
      - "5001:8080"
      - "8081:8081"
    depends_on:
      - postgresql
    environment:
      - ConnectionStrings__sqlConnection=Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=postgres;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https
  postgresql:
    image: postgres:16.2
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: