version: '3.4'

services:
  webaggregator:
    image: ${DOCKER_REGISTRY-}webaggregator
    container_name: webaggregator
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - postgresql
    environment:
      - ConnectionStrings__sqlConnection=Server=postgresql;Port=5432;Database=postgres;User Id=postgres;Password=postgres;
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/${MVMT_LOCAL_CERT_NAME}
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=${MVMT_LOCAL_CERT_PASS}
    # volumes:
    #   - ${MVMT_LOCAL_CERT_DIR}/:/https:ro
  postgresql:
    image: postgres:16.2
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

